import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 2, y = 2 }
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 100

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Underline", blinking = "On" }

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" }
]
